### ISSUE TITLE
No module named 'lwe.core.constants'

### ISSUE THREAD

**Issue by joshcho** [llm-workflow-engine/llm-workflow-engine#336]
**Describe the bug**
As in title, when using `pip install -e .` for dev.

Traceback (most recent call last):
  File "/home/pollock/.pyenv/versions/3.9.0/bin/lwe", line 5, in <module>
    from lwe.main import main
  File "/home/pollock/llm-workflow-engine/lwe/main.py", line 6, in <module>
    import lwe.core.constants as constants
ModuleNotFoundError: No module named 'lwe.core.constants'

**To Reproduce**
Just on the new version, trying to install.

**Expected behavior**

**Additional context**

**Comment by thehunmonkgroup** [comment]
How are you trying to install?

I did a pyenv install on Python 3.9.0 and it worked fine (you can ignore the missing plugin errors):

```
pip in /home/hunmonk/.pyenv/versions/3.9.0/envs/lwe-3.9/lib/python3.9/site-packages (20.2.3)
[:~/git/llm-workflow-engine] [lwe] main ± v .python-version
[:~/git/llm-workflow-engine] [lwe-3.9] main ± pip install git+https://github.com/llm-workflow-engine/llm-workflow-engine
Collecting git+https://github.com/llm-workflow-engine/llm-workflow-engine
  Cloning https://github.com/llm-workflow-engine/llm-workflow-engine to /tmp/pip-req-build-60sjcklt
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting names
  Using cached names-0.3.0.tar.gz (789 kB)
Collecting rich
  Downloading rich-13.7.0-py3-none-any.whl (240 kB)
     |████████████████████████████████| 240 kB 1.0 MB/s
Collecting prompt-toolkit
  Downloading prompt_toolkit-3.0.43-py3-none-any.whl (386 kB)
     |████████████████████████████████| 386 kB 3.0 MB/s
Collecting langchain<0.2,>=0.1
  Downloading langchain-0.1.4-py3-none-any.whl (803 kB)
     |████████████████████████████████| 803 kB 4.3 MB/s
Collecting PyYAML
  Downloading PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (738 kB)
     |████████████████████████████████| 738 kB 5.1 MB/s
Collecting textract@ git+https://github.com/thehunmonkgroup/textract@41c8a14de9facbfe21a1881cda49ced67b3bb5a4
  Cloning https://github.com/thehunmonkgroup/textract (to revision 41c8a14de9facbfe21a1881cda49ced67b3bb5a4) to /tmp/pip-install-z4geia5q/textract
Collecting pyperclip
  Using cached pyperclip-1.8.2.tar.gz (20 kB)
Collecting Jinja2
  Downloading Jinja2-3.1.3-py3-none-any.whl (133 kB)
     |████████████████████████████████| 133 kB 5.6 MB/s
Collecting ansible-core>=2.15
  Downloading ansible_core-2.15.8-py3-none-any.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 6.8 MB/s
Collecting docutils>=0.20.1
  Using cached docutils-0.20.1-py3-none-any.whl (572 kB)
Collecting alembic
  Downloading alembic-1.13.1-py3-none-any.whl (233 kB)
     |████████████████████████████████| 233 kB 10.2 MB/s
Collecting numexpr>=2.8.4
  Downloading numexpr-2.9.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (374 kB)
     |████████████████████████████████| 374 kB 11.8 MB/s
Collecting sqlalchemy>=1.4.48
  Downloading SQLAlchemy-2.0.25-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 11.3 MB/s
Collecting pdfminer.six
  Downloading pdfminer.six-20231228-py3-none-any.whl (5.6 MB)
     |████████████████████████████████| 5.6 MB 18.8 MB/s
Collecting openai~=1.6.1
  Downloading openai-1.6.1-py3-none-any.whl (225 kB)
     |████████████████████████████████| 225 kB 36.2 MB/s
Collecting ansible>=8.0
  Downloading ansible-8.7.0-py3-none-any.whl (48.4 MB)
     |████████████████████████████████| 48.4 MB 696 kB/s
Collecting python-frontmatter
  Downloading python_frontmatter-1.1.0-py3-none-any.whl (9.8 kB)
Collecting openpyxl
  Using cached openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
Collecting tiktoken
  Downloading tiktoken-0.5.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 32.0 MB/s
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 23.3 MB/s
Collecting email-validator
  Downloading email_validator-2.1.0.post1-py3-none-any.whl (32 kB)
Collecting langchain-openai
  Downloading langchain_openai-0.0.5-py3-none-any.whl (29 kB)
Collecting pygments<3.0.0,>=2.13.0
  Downloading pygments-2.17.2-py3-none-any.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 28.7 MB/s
Collecting markdown-it-py>=2.2.0
  Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting wcwidth
  Downloading wcwidth-0.2.13-py2.py3-none-any.whl (34 kB)
Collecting tenacity<9.0.0,>=8.1.0
  Using cached tenacity-8.2.3-py3-none-any.whl (24 kB)
Collecting dataclasses-json<0.7,>=0.5.7
  Downloading dataclasses_json-0.6.3-py3-none-any.whl (28 kB)
Collecting langchain-core<0.2,>=0.1.16
  Downloading langchain_core-0.1.16-py3-none-any.whl (230 kB)
     |████████████████████████████████| 230 kB 25.9 MB/s
Collecting requests<3,>=2
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting jsonpatch<2.0,>=1.33
  Downloading jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Collecting numpy<2,>=1
  Downloading numpy-1.26.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
     |████████████████████████████████| 18.2 MB 25.1 MB/s
Collecting langchain-community<0.1,>=0.0.14
  Downloading langchain_community-0.0.16-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 31.0 MB/s
Collecting pydantic<3,>=1
  Downloading pydantic-2.5.3-py3-none-any.whl (381 kB)
     |████████████████████████████████| 381 kB 17.0 MB/s
Collecting async-timeout<5.0.0,>=4.0.0; python_version < "3.11"
  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting langsmith<0.1,>=0.0.83
  Downloading langsmith-0.0.83-py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 8.7 MB/s
Collecting aiohttp<4.0.0,>=3.8.3
  Downloading aiohttp-3.9.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 30.8 MB/s
Collecting argcomplete>=1.10.0
  Downloading argcomplete-3.2.2-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 1.1 MB/s
Collecting chardet>=3.0
  Using cached chardet-5.2.0-py3-none-any.whl (199 kB)
Collecting docx2txt>=0.8
  Using cached docx2txt-0.8.tar.gz (2.8 kB)
Collecting extract-msg>=0.29.0
  Downloading extract_msg-0.47.0-py2.py3-none-any.whl (328 kB)
     |████████████████████████████████| 328 kB 20.9 MB/s
Collecting python-pptx>=0.6.18
  Downloading python_pptx-0.6.23-py3-none-any.whl (471 kB)
     |████████████████████████████████| 471 kB 21.9 MB/s
Collecting six>=1.12.0
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting SpeechRecognition>=3.8.1
  Downloading SpeechRecognition-3.10.1-py2.py3-none-any.whl (32.8 MB)
     |████████████████████████████████| 32.8 MB 19.5 MB/s
Collecting xlrd>=1.2.0
  Using cached xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting resolvelib<1.1.0,>=0.5.3
  Using cached resolvelib-1.0.1-py2.py3-none-any.whl (17 kB)
Collecting importlib-resources<5.1,>=5.0; python_version < "3.10"
  Downloading importlib_resources-5.0.7-py3-none-any.whl (24 kB)
Collecting packaging
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting cryptography
  Downloading cryptography-42.0.1-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
     |████████████████████████████████| 4.6 MB 26.4 MB/s
Collecting Mako
  Downloading Mako-1.3.0-py3-none-any.whl (78 kB)
     |████████████████████████████████| 78 kB 6.2 MB/s
Collecting typing-extensions>=4
  Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting greenlet!=0.4.17; platform_machine == "aarch64" or (platform_machine == "ppc64le" or (platform_machine == "x86_64" or (platform_machine == "amd64" or (platform_machine == "AMD64" or (platform_machine == "win32" or platform_machine == "WIN32")))))
  Downloading greenlet-3.0.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (660 kB)
     |████████████████████████████████| 660 kB 29.8 MB/s
Collecting charset-normalizer>=2.0.0
  Downloading charset_normalizer-3.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
     |████████████████████████████████| 142 kB 50.5 MB/s
Collecting httpx<1,>=0.23.0
  Downloading httpx-0.26.0-py3-none-any.whl (75 kB)
     |████████████████████████████████| 75 kB 6.0 MB/s
Collecting tqdm>4
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Collecting anyio<5,>=3.5.0
  Downloading anyio-4.2.0-py3-none-any.whl (85 kB)
     |████████████████████████████████| 85 kB 6.2 MB/s
Collecting sniffio
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting distro<2,>=1.7.0
  Downloading distro-1.9.0-py3-none-any.whl (20 kB)
Collecting et-xmlfile
  Using cached et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Collecting regex>=2022.1.18
  Downloading regex-2023.12.25-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (773 kB)
     |████████████████████████████████| 773 kB 22.8 MB/s
Collecting soupsieve>1.2
  Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Collecting dnspython>=2.0.0
  Downloading dnspython-2.5.0-py3-none-any.whl (305 kB)
     |████████████████████████████████| 305 kB 23.2 MB/s
Collecting idna>=2.0.0
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting typing-inspect<1,>=0.4.0
  Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Collecting marshmallow<4.0.0,>=3.18.0
  Downloading marshmallow-3.20.2-py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 9.9 MB/s
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Collecting jsonpointer>=1.9
  Downloading jsonpointer-2.4-py2.py3-none-any.whl (7.8 kB)
Collecting annotated-types>=0.4.0
  Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Collecting pydantic-core==2.14.6
  Downloading pydantic_core-2.14.6-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
     |████████████████████████████████| 2.1 MB 14.7 MB/s
Collecting attrs>=17.3.0
  Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
     |████████████████████████████████| 60 kB 8.7 MB/s
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     |████████████████████████████████| 114 kB 22.8 MB/s
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.4-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (304 kB)
     |████████████████████████████████| 304 kB 26.9 MB/s
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (240 kB)
     |████████████████████████████████| 240 kB 22.1 MB/s
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting red-black-tree-mod==1.20
  Using cached red-black-tree-mod-1.20.tar.gz (28 kB)
Collecting tzlocal<6,>=4.2
  Downloading tzlocal-5.2-py3-none-any.whl (17 kB)
Collecting RTFDE<0.2,>=0.1.1
  Downloading RTFDE-0.1.1-py3-none-any.whl (36 kB)
Collecting olefile==0.47
  Downloading olefile-0.47-py2.py3-none-any.whl (114 kB)
     |████████████████████████████████| 114 kB 32.1 MB/s
Collecting ebcdic<2,>=1.1.1
  Using cached ebcdic-1.1.1-py2.py3-none-any.whl (128 kB)
Collecting compressed-rtf<2,>=1.0.6
  Using cached compressed_rtf-1.0.6.tar.gz (5.8 kB)
Collecting XlsxWriter>=0.5.7
  Downloading XlsxWriter-3.1.9-py3-none-any.whl (154 kB)
     |████████████████████████████████| 154 kB 33.2 MB/s
Collecting Pillow>=3.3.2
  Downloading pillow-10.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
     |████████████████████████████████| 4.4 MB 28.0 MB/s
Collecting lxml>=3.1.0
  Downloading lxml-5.1.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (8.0 MB)
     |████████████████████████████████| 8.0 MB 22.4 MB/s
Collecting cffi>=1.12; platform_python_implementation != "PyPy"
  Downloading cffi-1.16.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (443 kB)
     |████████████████████████████████| 443 kB 24.5 MB/s
Collecting httpcore==1.*
  Downloading httpcore-1.0.2-py3-none-any.whl (76 kB)
     |████████████████████████████████| 76 kB 6.3 MB/s
Collecting exceptiongroup>=1.0.2; python_version < "3.11"
  Downloading exceptiongroup-1.2.0-py3-none-any.whl (16 kB)
Collecting mypy-extensions>=0.3.0
  Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting lark==1.1.8
  Downloading lark-1.1.8-py3-none-any.whl (111 kB)
     |████████████████████████████████| 111 kB 24.1 MB/s
Collecting oletools>=0.56
  Using cached oletools-0.60.1-py2.py3-none-any.whl (977 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting h11<0.15,>=0.13
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting easygui
  Using cached easygui-0.98.3-py2.py3-none-any.whl (92 kB)
Collecting pcodedmp>=1.2.5
  Using cached pcodedmp-1.2.6-py2.py3-none-any.whl (30 kB)
Collecting colorclass
  Using cached colorclass-2.2.2-py2.py3-none-any.whl (18 kB)
Collecting pyparsing<3,>=2.1.0
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting msoffcrypto-tool; platform_python_implementation != "PyPy" or (python_version >= "3" and platform_system != "Windows" and platform_system != "Darwin")
  Downloading msoffcrypto_tool-5.3.1-py3-none-any.whl (46 kB)
     |████████████████████████████████| 46 kB 4.7 MB/s
Using legacy 'setup.py install' for names, since package 'wheel' is not installed.
Using legacy 'setup.py install' for textract, since package 'wheel' is not installed.
Using legacy 'setup.py install' for pyperclip, since package 'wheel' is not installed.
Using legacy 'setup.py install' for docx2txt, since package 'wheel' is not installed.
Using legacy 'setup.py install' for red-black-tree-mod, since package 'wheel' is not installed.
Using legacy 'setup.py install' for compressed-rtf, since package 'wheel' is not installed.
Building wheels for collected packages: llm-workflow-engine
  Building wheel for llm-workflow-engine (PEP 517) ... done
  Created wheel for llm-workflow-engine: filename=llm_workflow_engine-0.18.8-py3-none-any.whl size=157298 sha256=31f0765fd956865b8dd610b46acb6ccb5a538065d4548b990c8d073b24b1fe2d
  Stored in directory: /tmp/pip-ephem-wheel-cache-6pxpuluv/wheels/59/0d/af/a6725b50cd600cec856fb596b306cb8abae3ba41fac9ab3fda
Successfully built llm-workflow-engine
Installing collected packages: names, pygments, mdurl, markdown-it-py, rich, wcwidth, prompt-toolkit, tenacity, mypy-extensions, typing-extensions, typing-inspect, packaging, marshmallow, dataclasses-json, charset-normalizer, idna, urllib3, certifi, requests, jsonpointer, jsonpatch, sniffio, exceptiongroup, anyio, PyYAML, annotated-types, pydantic-core, pydantic, langsmith, langchain-core, numpy, greenlet, sqlalchemy, attrs, multidict, yarl, frozenlist, aiosignal, async-timeout, aiohttp, langchain-community, langchain, argcomplete, soupsieve, beautifulsoup4, chardet, docx2txt, red-black-tree-mod, tzlocal, lark, easygui, pcodedmp, olefile, colorclass, pyparsing, pycparser, cffi, cryptography, msoffcrypto-tool, oletools, RTFDE, ebcdic, compressed-rtf, extract-msg, pdfminer.six, XlsxWriter, Pillow, lxml, python-pptx, six, SpeechRecognition, xlrd, et-xmlfile, openpyxl, textract, pyperclip, MarkupSafe, Jinja2, resolvelib, importlib-resources, ansible-core, docutils, Mako, alembic, numexpr, h11, httpcore, httpx, tqdm, distro, openai, ansible, python-frontmatter, regex,tiktoken, dnspython, email-validator, langchain-openai, llm-workflow-engine
    Running setup.py install for names ... done
    Running setup.py install for docx2txt ... done
    Running setup.py install for red-black-tree-mod ... done
    Running setup.py install for compressed-rtf ... done
    Running setup.py install for textract ... done
    Running setup.py install for pyperclip ... done
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

langchain-openai 0.0.5 requires openai<2.0.0,>=1.10.0, but you'll have openai 1.6.1 which is incompatible.
Successfully installed Jinja2-3.1.3 Mako-1.3.0 MarkupSafe-2.1.4 Pillow-10.2.0 PyYAML-6.0.1 RTFDE-0.1.1 SpeechRecognition-3.10.1 XlsxWriter-3.1.9 aiohttp-3.9.1 aiosignal-1.3.1 alembic-1.13.1 annotated-types-0.6.0 ansible-8.7.0 ansible-core-2.15.8 anyio-4.2.0 argcomplete-3.2.2 async-timeout-4.0.3 attrs-23.2.0 beautifulsoup4-4.12.3 certifi-2023.11.17 cffi-1.16.0 chardet-5.2.0 charset-normalizer-3.3.2 colorclass-2.2.2 compressed-rtf-1.0.6 cryptography-42.0.1 dataclasses-json-0.6.3 distro-1.9.0 dnspython-2.5.0 docutils-0.20.1 docx2txt-0.8 easygui-0.98.3 ebcdic-1.1.1 email-validator-2.1.0.post1 et-xmlfile-1.1.0 exceptiongroup-1.2.0 extract-msg-0.47.0 frozenlist-1.4.1 greenlet-3.0.3 h11-0.14.0 httpcore-1.0.2 httpx-0.26.0 idna-3.6 importlib-resources-5.0.7 jsonpatch-1.33 jsonpointer-2.4 langchain-0.1.4 langchain-community-0.0.16 langchain-core-0.1.16 langchain-openai-0.0.5 langsmith-0.0.83 lark-1.1.8 llm-workflow-engine-0.18.8 lxml-5.1.0 markdown-it-py-3.0.0 marshmallow-3.20.2 mdurl-0.1.2 msoffcrypto-tool-5.3.1 multidict-6.0.4 mypy-extensions-1.0.0 names-0.3.0 numexpr-2.9.0 numpy-1.26.3 olefile-0.47 oletools-0.60.1 openai-1.6.1 openpyxl-3.1.2 packaging-23.2 pcodedmp-1.2.6 pdfminer.six-20231228 prompt-toolkit-3.0.43 pycparser-2.21 pydantic-2.5.3 pydantic-core-2.14.6 pygments-2.17.2 pyparsing-2.4.7 pyperclip-1.8.2 python-frontmatter-1.1.0 python-pptx-0.6.23 red-black-tree-mod-1.20 regex-2023.12.25 requests-2.31.0 resolvelib-1.0.1 rich-13.7.0 six-1.16.0 sniffio-1.3.0 soupsieve-2.5 sqlalchemy-2.0.25 tenacity-8.2.3 textract-1.7.0 tiktoken-0.5.2 tqdm-4.66.1 typing-extensions-4.9.0 typing-inspect-0.9.0 tzlocal-5.2 urllib3-2.1.0 wcwidth-0.2.13 xlrd-2.0.1 yarl-1.9.4
WARNING: You are using pip version 20.2.3; however, version 23.3.2 is available.
You should consider upgrading via the '/home/hunmonk/.pyenv/versions/3.9.0/envs/lwe-3.9/bin/python3.9 -m pip install --upgrade pip' command.
[:~/git/llm-workflow-engine] [lwe-3.9] main ± alias lwe
alias lwe='cd ~/git/llm-workflow-engine && lwe --log ~/.local/share/llm-workflow-engine/logs/2024-01-25.log'
[:~/git/llm-workflow-engine] [lwe-3.9] main ± unalias lwe
[:~/git/llm-workflow-engine] [lwe-3.9] main ± alias lwe
bash: alias: lwe: not found
[:~/git/llm-workflow-engine] [lwe-3.9] main 1 ± lwe
PluginManager - ERROR - Plugin pastebin not found in search path
PluginManager - ERROR - Plugin provider_chat_anthropic not found in search path
PluginManager - ERROR - Plugin provider_chat_cohere not found in search path
PluginManager - ERROR - Plugin provider_chat_ollama not found in search path
PluginManager - ERROR - Plugin shell not found in search path
PluginManager - ERROR - Plugin gist not found in search path
PluginManager - ERROR - Plugin provider_chat_mistralai not found in search path
PluginManager - ERROR - Plugin provider_chat_google_genai not found in search path
ProviderManager - ERROR - Provider provider_chat_mistralai not found in provider_plugins.
Failed to load default preset mistral: Provider provider_chat_mistralai not found in provider_plugins.

ProviderManager - ERROR - Provider provider_chat_mistralai not found in provider_plugins.
Failed to load default preset mistral: Provider provider_chat_mistralai not found in provider_plugins.


                                        Provide a prompt, or type /help or ? to list commands.

[New Conversation]
(0.7/16384/0): default
hunmonk@gpt-3.5-turbo-1106 1>
```

**Comment by thehunmonkgroup** [comment]
Closing due to lack of response.
