### ISSUE TITLE
No Windows console found. Are you running cmd.exe?

### ISSUE THREAD

**Issue by johnd0e** [llm-workflow-engine/llm-workflow-engine#338]
`lwe config>config.yaml`

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\OpenAI\llm-workflow-engine\venv\Scripts\lwe.exe\__main__.py", line 7, in <module>
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\main.py", line 175, in main
    shell = ApiRepl(config)
            ^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\backends\api\repl.py", line 28, in __init__
    super().__init__(config)
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\core\repl.py", line 62, in __init__
    self.prompt_session = PromptSession(
                          ^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 467, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 718, in _create_application
    application: Application[_T] = Application(
                                   ^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\application\application.py", line 267, in __init__
    self.output = output or session.output
                            ^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\application\current.py", line 67, in output
    self._output = create_output()
                   ^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\output\defaults.py", line 87, in create_output
    return Win32Output(stdout, default_color_depth=color_depth_from_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\output\win32.py", line 115, in __init__
    info = self.get_win32_screen_buffer_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\output\win32.py", line 219, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.output.win32.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?
```

**Comment by johnd0e** [comment]
> I don't understand your report, what are you trying to accomplish?

I tried to get default config in file, but that is not really important.

The problem is that i cannot use output redirection with lwe.
Consider this example:
```
lwe hi there!>output
```

**Comment by thehunmonkgroup** [comment]
```
[:~/git/llm-workflow-engine] [lwe] main+ ± lwe --help
usage: lwe [-h] [--version] [-c CONFIG_DIR] [-p CONFIG_PROFILE] [-t DATA_DIR] [-r PRESET] [-s ALIAS_NAME] [-i [INPUT_FILE]] [-l LOG]
           [-n] [--database DATABASE] [-w WORKFLOW] [--workflow-args WORKFLOW_ARGS] [--template-dir PATH] [--preset-dir PATH]
           [--plugin-dir PATH] [--workflow-dir PATH] [--function-dir PATH] [-d] [-e FILEPATH]
           [params ...]

positional arguments:
  params                Use 'config' to see current configuration, or provide a prompt.

options:
  -h, --help            show this help message and exit
  --version, -v         Print version and exit.
  -c CONFIG_DIR, --config-dir CONFIG_DIR
                        Directory to read config from (default: /home/hunmonk/.config/llm-workflow-engine)
  -p CONFIG_PROFILE, --config-profile CONFIG_PROFILE
                        Config profile to use (default: default)
  -t DATA_DIR, --data-dir DATA_DIR
                        Directory to read/store data from (default: /home/hunmonk/.local/share/llm-workflow-engine)
  -r PRESET, --preset PRESET
                        Preset to use on startup
  -s ALIAS_NAME, --system-message ALIAS_NAME
                        Alias name of the system message to use on startup
  -i [INPUT_FILE], --input-file [INPUT_FILE]
                        Input file (default: read from stdin)
  -l LOG, --log LOG     Log prompts and responses to the named file
  -n, --no-stream       Disable streaming mode
  --database DATABASE   Database to store chat-related data (default: sqlite:////home/hunmonk/.local/share/llm-workflow-
                        engine/profiles/default/storage.db)
  -w WORKFLOW, --workflow WORKFLOW
                        Workflow to run
  --workflow-args WORKFLOW_ARGS
                        Arguments to pass to the workflow
  --template-dir PATH   User template directory (can be specified multiple times)
  --preset-dir PATH     User preset directory (can be specified multiple times)
  --plugin-dir PATH     User plugin directory (can be specified multiple times)
  --workflow-dir PATH   User workflow directory (can be specified multiple times)
  --function-dir PATH   User function directory (can be specified multiple times)
  -d, --debug           Enable debug mode
  -e FILEPATH, --debug-log FILEPATH
                        Debug logging to FILEPATH
[:~/git/llm-workflow-engine] [lwe] main+ ± lwe -n say hello > ~/Downloads/hello.txt
[:~/git/llm-workflow-engine] [lwe] main+ ± cat -p ~/Downloads/hello.txt

Hello! How can I assist you today? Is there something specific you would like help with? I'm here to make your life easier in any way I
can. Whether you need help with scheduling, research, or just have a question about a topic you're curious about, I'm happy to help.
Let me know what you need and I'll do my best to assist you. I look forward to working with you!
```

**Comment by johnd0e** [comment]
```
D:\OpenAI\llm-workflow-engine\venv\Scripts>lwe -n say hello > hello.txt
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\OpenAI\llm-workflow-engine\venv\Scripts\lwe.exe\__main__.py", line 7, in <module>
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\main.py", line 175, in main
    shell = ApiRepl(config)
            ^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\backends\api\repl.py", line 28, in __init__
    super().__init__(config)
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\lwe\core\repl.py", line 62, in __init__
    self.prompt_session = PromptSession(
                          ^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 467, in __init__
    self.app = self._create_application(editing_mode, erase_when_done)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\shortcuts\prompt.py", line 718, in _create_application
    application: Application[_T] = Application(
                                   ^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\application\application.py", line 267, in __init__
    self.output = output or session.output
                            ^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\application\current.py", line 67, in output
    self._output = create_output()
                   ^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\output\defaults.py", line 87, in create_output
    return Win32Output(stdout, default_color_depth=color_depth_from_env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\output\win32.py", line 115, in __init__
    info = self.get_win32_screen_buffer_info()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\OpenAI\llm-workflow-engine\venv\Lib\site-packages\prompt_toolkit\output\win32.py", line 219, in get_win32_screen_buffer_info
    raise NoConsoleScreenBufferError
prompt_toolkit.output.win32.NoConsoleScreenBufferError: No Windows console found. Are you running cmd.exe?
```

**Comment by thehunmonkgroup** [comment]
Can't really help you any more on this one. I'm not a Windows user, and I've already burned many hours getting LWE to work on Windows.

The community will need to step up to improve Windows support. Please feel free to submit a quality PR that addresses this issue.

**Comment by johnd0e** [comment]
Fair enough

**Comment by thehunmonkgroup** [comment]
Can you try running `cmd.exe` to get an interactive shell, then running `lwe -n say hello > hello.txt`

**Comment by johnd0e** [comment]
That is exactly what I have done before.
I have just repeat it, and got the same traceback.

**Comment by thehunmonkgroup** [comment]
Looks like this is a long-standing issue w/ prompt-toolkit, which LWE uses for its CLI functionality:

https://github.com/prompt-toolkit/python-prompt-toolkit/issues/406

You may want to investigate that issue.

Closing this one, as the bug is not located in this project
