### ISSUE TITLE
AttributeError: 'EntryPoint' object has no attribute 'dist'

### ISSUE THREAD

**Issue by nfedyashev** [llm-workflow-engine/llm-workflow-engine#347]
**Describe the bug**
Initial setup seems instructions to be failing

**To Reproduce**
```
python --version
# Python 3.9.2
```

```
pip install git+https://github.com/llm-workflow-engine/llm-workflow-engine                     
# Installing collected packages: llm-workflow-engine
# Successfully installed llm-workflow-engine-0.20.1
```

```
lwe config                                              
Traceback (most recent call last):
  File "/home/username/.local/bin/lwe", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.9/site-packages/lwe/main.py", line 188, in main
    shell.setup()
  File "/home/username/.local/lib/python3.9/site-packages/lwe/core/repl.py", line 320, in setup
    self.configure_backend()
  File "/home/username/.local/lib/python3.9/site-packages/lwe/backends/api/repl.py", line 95, in configure_backend
    self.backend = ApiBackend(self.config)
  File "/home/username/.local/lib/python3.9/site-packages/lwe/backends/api/backend.py", line 51, in __init__
    self.initialize_backend(config)
  File "/home/username/.local/lib/python3.9/site-packages/lwe/backends/api/backend.py", line 180, in initialize_backend
    self.plugin_manager = PluginManager(
  File "/home/username/.local/lib/python3.9/site-packages/lwe/core/plugin_manager.py", line 31, in __init__
    self.load_package_plugins(self.plugin_list)
  File "/home/username/.local/lib/python3.9/site-packages/lwe/core/plugin_manager.py", line 93, in load_package_plugins
    package_name = entry_point.dist.metadata["Name"]
AttributeError: 'EntryPoint' object has no attribute 'dist'
```

**Comment by thehunmonkgroup** [comment]
99% sure this is an issue with the compat code for older Python versions:

https://github.com/llm-workflow-engine/llm-workflow-engine/blob/main/lwe/core/plugin_manager.py#L90-L91

I'll need to poke around and see if I can get that working again. In the mean time, you can try installing LWE in a virtualenv with a new Python version.

**Comment by thehunmonkgroup** [comment]
Should be fixed in latest release: https://github.com/llm-workflow-engine/llm-workflow-engine/releases/tag/v0.20.2

Thanks for the report.

**Comment by nfedyashev** [comment]
@thehunmonkgroup 0.20.2 release fixed it. Thank you!
