### ISSUE TITLE
LWE (installed via pipx) exits with error on Alpine Linux (v3.19)

### ISSUE THREAD

**Issue by ForeverNooob** [llm-workflow-engine/llm-workflow-engine#350]
**Describe the bug**
I tried to run LWE, but it crashed with an error.

**To Reproduce**
Install Alpine Linux v3.19 (in a VM), then run the commands below.

**Additional context**

Scroll all the way down to the bottom to skip many of my installation woes on Alpine.

```
└─$  cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.4
PRETTY_NAME="Alpine Linux v3.19"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"

# tl;dr just do this to avoid the stuff below: doas apk add python3 py3-pip
└─$  doas apk add python3
(1/14) Installing mpdecimal (2.5.1-r2)
(2/14) Installing libpanelw (6.4_p20231125-r0)
(3/14) Installing python3 (3.11.10-r0)
(4/14) Installing python3-pycache-pyc0 (3.11.10-r0)
(5/14) Installing pyc (3.11.10-r0)
(6/14) Installing python3-pyc (3.11.10-r0)
(7/14) Installing py3-parsing (3.1.1-r0)
(8/14) Installing py3-parsing-pyc (3.1.1-r0)
(9/14) Installing py3-packaging (23.2-r0)
(10/14) Installing py3-packaging-pyc (23.2-r0)
(11/14) Installing py3-setuptools (70.3.0-r0)
(12/14) Installing py3-setuptools-pyc (70.3.0-r0)
(13/14) Installing py3-capstone (5.0.1-r1)
(14/14) Installing py3-capstone-pyc (5.0.1-r1)
Executing busybox-1.36.1-r19.trigger
OK: 288 MiB in 144 packages



└─$  pip
-bash: pip: command not found

└─$  python -m ensurepip
error: externally-managed-environment

× This environment is externally managed
╰─>
    The system-wide python installation should be maintained using the system
    package manager (apk) only.

    If the package in question is not packaged already (and hence installable via
    "apk add py3-somepackage"), please consider installing it inside a virtual
    environment, e.g.:

    python3 -m venv /path/to/venv
    . /path/to/venv/bin/activate
    pip install mypackage

    To exit the virtual environment, run:

    deactivate

    The virtual environment is not deleted, and can be re-entered by re-sourcing
    the activate file.

    To automatically manage virtual environments, consider using pipx (from the
    pipx package).

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ensurepip/__init__.py", line 286, in _main
    return _bootstrap(
           ^^^^^^^^^^^
  File "/usr/lib/python3.11/ensurepip/__init__.py", line 202, in _bootstrap
    return _run_pip([*args, *_PACKAGE_NAMES], additional_paths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ensurepip/__init__.py", line 103, in _run_pip
    return subprocess.run(cmd, check=True).returncode
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python', '-W', 'ignore::DeprecationWarning', '-c', '\nimport runpy\nimport sys\nsys.path = [\'/tmp/tmp4g9bgoas/setuptools-65.5.0-py3-none-any.whl\', \'/tmp/tmp4g9bgoas/pip-24.0-py3-none-any.whl\'] + sys.path\nsys.argv[1:] = [\'install\', \'--no-cache-dir\', \'--no-index\', \'--find-links\', \'/tmp/tmp4g9bgoas\', \'setuptools\', \'pip\']\nrunpy.run_module("pip", run_name="__main__", alter_sys=True)\n']' returned non-zero exit status 1.


└─$  doas apk add py3-pip
(1/2) Installing py3-pip-pyc (23.3.1-r0)
(2/2) Installing py3-pip (23.3.1-r0)
Executing busybox-1.36.1-r19.trigger
OK: 305 MiB in 146 packages

└─$  pip -V
pip 23.3.1 from /usr/lib/python3.11/site-packages/pip (python 3.11)



# After seeing this answer: https://stackoverflow.com/a/75722775
└─$  doas apk add pipx
doas (alp@vmalp) password:
(1/12) Installing py3-colorama (0.4.6-r3)
(2/12) Installing py3-colorama-pyc (0.4.6-r3)
(3/12) Installing py3-platformdirs (4.0.0-r0)
(4/12) Installing py3-platformdirs-pyc (4.0.0-r0)
(5/12) Installing py3-click (8.1.7-r0)
(6/12) Installing py3-click-pyc (8.1.7-r0)
(7/12) Installing py3-userpath (1.9.1-r0)
(8/12) Installing py3-userpath-pyc (1.9.1-r0)
(9/12) Installing pipx-pyc (1.4.3-r0)
(10/12) Installing py3-argcomplete-pyc (3.1.6-r0)
(11/12) Installing py3-argcomplete (3.1.6-r0)
(12/12) Installing pipx (1.4.3-r0)
Executing busybox-1.36.1-r19.trigger
OK: 308 MiB in 158 packages


└─$  pipx install git+https://github.com/llm-workflow-engine/llm-workflow-engine
  installed package llm-workflow-engine 0.22.2, installed using Python 3.11.10
  These apps are now globally available
    - lwe
done! ✨ 🌟 ✨


└─$  lwe
Creating database schema for: sqlite:////home/alp/.local/share/llm-workflow-engine/profiles/default/storage.db

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> 4e642f725923
Database schema installed

Traceback (most recent call last):
  File "/home/alp/.local/bin/lwe", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/lwe/main.py", line 188, in main
    shell.setup()
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/lwe/core/repl.py", line 301, in setup
    self.configure_backend()
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/lwe/backends/api/repl.py", line 95, in configure_backend
    self.backend = ApiBackend(self.config)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/lwe/backends/api/backend.py", line 54, in __init__
    self.initialize_backend(self.config)
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/lwe/backends/api/backend.py", line 176, in initialize_backend
    self.plugin_manager = PluginManager(
                          ^^^^^^^^^^^^^^
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/lwe/core/plugin_manager.py", line 32, in __init__
    self.load_plugins(self.plugin_list)
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/lwe/core/plugin_manager.py", line 68, in load_plugins
    plugin_instance = self.load_plugin(plugin_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/lwe/core/plugin_manager.py", line 150, in load_plugin
    if not self.setup_plugin(plugin_name, plugin_instance):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/lwe/core/plugin_manager.py", line 125, in setup_plugin
    plugin_instance.setup()
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/lwe/core/provider.py", line 117, in setup
    self.set_customizations(self.default_customizations())
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/lwe/core/provider.py", line 153, in default_customizations
    llm = llm_class(**defaults)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/langchain_core/load/serializable.py", line 125, in __init__
    super().__init__(*args, **kwargs)
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/langchain_openai/chat_models/base.py", line 551, in validate_environment
    self.root_client = openai.OpenAI(**client_params, **sync_specific)  # type: ignore[arg-type]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alp/.local/share/pipx/venvs/llm-workflow-engine/lib/python3.11/site-packages/openai/_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

**Comment by thehunmonkgroup** [comment]
The last error gives you the instructions to fix the problem:

`
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
`

LWE requires an OpenAI API key to work. If you're not intending to use OpenAI, but one of the other provider plugins, you could probably get away with setting `OPENAI_API_KEY` to some non-empty value just to get past the validation check -- but of course OpenAI LLM calls would not work in that case.
